# Project information
site_name: 'PeachPie Documentation'
site_description: 'PeachPie - PHP Compiler for .NET - Documentation'
site_author: 'peachpie'
site_url: 'https://docs.peachpie.io'

# Repository
repo_name: 'peachpiecompiler/peachpie'
repo_url: 'https://github.com/peachpiecompiler/peachpie'
edit_uri: 'https://github.com/peachpiecompiler/peachpie-docs/edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2020 iolevel s.r.o.'

# Configuration
theme:
  name: 'material'
  custom_dir: 'custom_theme'
  language: 'en'
  palette:
    primary: 'deep orange'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
    
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Customization
extra_css:
  - extra.css

extra:
  social:
    - type: 'home'
      link: 'https://www.peachpie.io/'
    - type: 'github'
      link: 'https://github.com/peachpiecompiler/peachpie'
    - type: 'twitter'
      link: 'https://twitter.com/pchpcompiler'
  search:
    language: 'en'

# Google Analytics
google_analytics:
  - 'UA-73282519-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.progressbar
  - codehilite:
      guess_lang: false
  - toc:
      permalink: "#"

# plugins
plugins:
    - search
    - awesome-pages
